### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mokryboss** [begateway/woocommerce-payment-module#2]
Wordpress 4.8.2
Woocommerce 3.1.2+
PHP 7.1.6

Ошибка при активации плагина:
![error](https://user-images.githubusercontent.com/22744045/31767291-2b63b518-b4d3-11e7-8eae-805be3ff4850.png)

**Comment by pax-by** [comment]
Пожалуйста, переименуйте класс в репозитории, аналогичная ошибка при активации.

**Comment by avsh** [comment]
Модуль обновлен для работы с PHP 7
