### ISSUE TITLE
Order Status

### ISSUE THREAD

**Issue by vralle** [begateway/woocommerce-payment-module#7]
После успешной оплаты в тестовом режиме статус Заказа не поменялся. Остался в "Ожидании оплаты". WooCommerce на странице Заказа предлагает оплатить или отменить. Также нигде не проходит поступление средств. Не уверен, что это нормальное поведение.

**Comment by avsh** [comment]
Надо настроить проброс заголовков авторизации в php скрипты. Мы не можем валидировать колбэк и поэтому статус не меняется
